title: UniVoice Support
description: Official support site for the UniVoice speech translation app.
theme: jekyll-theme-minimal

# Optional: set baseurl only if deploying to a subdirectory (not needed for standard GitHub Pages)
# baseurl: "/univoice_support"

# Enable Markdown rendering and pages
markdown: kramdown
